import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Flowbite, ThemeModeScript } from "flowbite-react";
import "@/utilities/styles/globals.css";
import { flowbiteTheme } from "@/utilities/configs/flowbiteTheme";
import { GlobalContextWrapper } from "@/utilities/components/layouts/global/_partials/GlobalContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Flowbite React",
  description: "Generated by create flowbite react",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.className}>
      <head suppressHydrationWarning>
        <ThemeModeScript />
      </head>
      <body>
        <Flowbite theme={{ theme: flowbiteTheme }}>
          <GlobalContextWrapper>
            {children}
          </GlobalContextWrapper>
        </Flowbite>
      </body>
    </html>
  );
}
